# -*- coding: utf-8 -*-
"""Copy of StudentCopy of CO1 - NumpyArray.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1enF65At94_-s923zOAeP80pHOzmAWwZS
"""

# program to create an array of all the even integers from 20 to 80
import numpy as np
x = np.arange(start=20,stop=81,step=2)
print("Even Integers From 20 - 80:-")
print(x)

#Write a program to create a numpy array and perform element-wise comparison (greater, greater_equal, less than, lesser_equal).
import numpy as np
x = np.array([12,45,11,18])
y = np.array([14,17,80,18])

print("Array A:",x)
print("Array B:",y)

print("Greater||>")
print(np.greater(x,y))
print("\n")
print("Less||<")
print(np.less(x,y))
print("\n")
print("GreaterOrEqualTo||>=")
print(np.greater_equal(x,y))
print("\n")
print("LessOrEqualTo||<=")
print(np.less_equal(x,y))

#program to multiply two given arrays of same size
import numpy as np
arr1 = np.array([[[1,2,3],[3,2,1],[9,8,7]]]).reshape(3,3)
arr2 = np.array([[[9,8,7],[3,2,1],[5,4,7]]]).reshape(3,3)
print("First Array")
print(arr1)
print("Second Array:")
print(arr2)

print("Multiplication of two array")
print(np.multiply(arr1,arr2))

#Program to save a given array to a text file and load it
import numpy as np
import os

arr1 = np.arange(start=0,stop=16).reshape(4,4)
print(arr1)

h = 'c1 c2 c3 c4'
np.savetxt("File.txt",arr1,fmt="%d",header=h)
print("From File.txt Using loadtxt()")
print(np.loadtxt("File.txt"))